#
# If you are using the readsb container to pull your feed from, you may have add the following environment
# variables to the readsb section:
#      - READSB_NET_BEAST_OUTPUT_PORT=30005
#      - READSB_NET_RAW_OUTPUT_PORT=30002
#
# Also, it assumes that you have added the following parameters to your `.env` file., or made available in this docker-compose.yml file:
#
# RV_FEEDER_KEY=xxxx:123456789ABCDEF
# FEEDER_LAT=12.345678
# FEEDER_LONG=6.7890123
# FEEDER_ALT_M=12.3
#
# Once everything runs to your liking, feel free to set VERBOSE=OFF
#

services:
  radarvirtuel:
    image: ghcr.io/sdr-enthusiasts/docker-radarvirtuel
    container_name: radarvirtuel
    hostname: radarvirtuel
    restart: always
    environment:
      # BEASTHOST: ADSB data source in Beast format. Default value if omitted: "Ultrafeeder"
      - BEASTHOST=
      # RV_CONTRIB_NAME and RV_CONTRIB_EMAIL: Mandatory parameters! Container won't run without them.
      - RV_CONTRIB_NAME=
      - RV_CONTRIB_EMAIL=
      # LAT / LON / ALT_M: mandatory parameters!
      - LAT=${FEEDER_LAT}
      - LON=${FEEDER_LONG}
      - ALT_M=${FEEDER_ALT_M:-0}
    tmpfs:
      - /tmp:rw,nosuid,nodev,noexec,relatime
    volumes:
      - "./rv_data:/data:rw"
      - "/proc/cpuinfo:/host/cpuinfo:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
