#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2145,SC2154

#---------------------------------------------------------------------------------------------
# Copyright (C) 2023-2024, Ramon F. Kolb (kx1t) and contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

source /scripts/common

if chk_disabled "${ENABLE_MLAT}"; then
    "${s6wrap[@]}" echo "MLAT is DISABLED (ENABLE_MLAT is set to $ENABLE_MLAT)"
    stop_service
fi

if [[ -n "$RV_SERVER" || -n "$FEEDER_KEY" || -z "$RV_CONTRIB_NAME" || -z "$RV_CONTRIB_EMAIL" ]]; then
    stop_service
fi

### TEMP DISABLE MLAT
# stop_service

"${s6wrap[@]}" echo "Started as an s6 service"

MLAT_CMD="/usr/local/bin/mlat-client"

MLAT_INPUT_TYPE="${MLAT_INPUT_TYPE:-auto}"
MLAT_RESULTS="${MLAT_RESULTS:-beast,listen,30105}"

BEASTHOST="${BEASTHOST:-${SOURCE_HOST:-ultrafeeder}}"
BEASTHOST="${BEASTHOST%%:*}"
BEASTPORT="${BEASTPORT:-${SOURCE_PORT:-30005}}"
if [[ "$BEASTPORT" == "30002" ]]; then
		BEASTPORT="30005"
fi

MLAT_HOST="${MLAT_HOST:-$BEASTHOST:$BEASTPORT}"

RV_LAT="${RV_LAT:-$LAT}"
RV_LON="${RV_LON:-$LON}"
RV_ALT="${RV_ALT:-${RV_ALT_M:-${ALT_M:-${ALT:-0}}}}"

# If MLAT_HOST is not defined, use port 30005 (beast_out) on the SOURCE_HOST

START_DELAY=15s

# don't start MLAT until we have the station ID and UID
while [[ ! -f /data/station_id.txt || ! -f /data/station_uid.txt ]]; do
	sleep 1
done

MLAT_PARAM=(--input-type beast)
MLAT_PARAM+=(--input-connect "${MLAT_HOST}")
MLAT_PARAM+=(--server "${MLAT_SERVER:-mlat.adsbnetwork.com:50000}")
MLAT_PARAM+=(--lat "${RV_LAT}")
MLAT_PARAM+=(--lon "${RV_LON}")
MLAT_PARAM+=(--alt "${RV_ALT}")
MLAT_PARAM+=(--results "${MLAT_RESULTS}")
MLAT_PARAM+=(--user "$(</data/station_id.txt)")
MLAT_PARAM+=(--uuid "$(</data/station_uid.txt)")
if chk_enabled "$PRIVATE_MLAT"; then MLAT_PARAM+=("--privacy"); fi

sleep ${START_DELAY}

if chk_enabled "${VERBOSE}"; then
	"${s6wrap[@]}" echo "Starting MLAT with: ${MLAT_CMD} ${MLAT_PARAM[@]}"
	exec "${s6wrap[@]}" "${MLAT_CMD}" "${MLAT_PARAM[@]}"
else
	exec "${s6wrap[@]}" "${MLAT_CMD}" "${MLAT_PARAM[@]}"
fi
