#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2145

source /scripts/common

APPNAME="mlat-client"
s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "Started as an s6 service"

MLAT_CMD="/usr/bin/mlat-client"
MLAT_FLAG="/run/mlat-down"

MLAT_INPUT_TYPE="${MLAT_INPUT_TYPE:-auto}"
MLAT_RESULTS="${MLAT_RESULTS:-beast,listen,30105}"

START_DELAY=10s

# Do some basic checks:
# Sleep forever if the initialization process found that MLAT cannot be started
[[ -f ${MLAT_FLAG} ]] && [[ "$(<${MLAT_FLAG})" != "temp" ]] && sleep infinity || true
# Sleep for 5 minutes if the issue is that the config is correct but the server is down
if [[ -f ${MLAT_FLAG} ]] && [[ "$(<${MLAT_FLAG})" == "temp" ]]
then
	if [[ $(timeout --preserve-status 10 netcat -z -v "${MLAT_SERVER%%:*}" "${MLAT_SERVER##*:}" 2>/dev/null ; echo $?) != "0" ]] \
  		|| [[ $(timeout --preserve-status 10 netcat -z -v "${MLAT_HOST%%:*}" "${MLAT_HOST##*:}" 2>/dev/null ; echo $?) != "0" ]]
	then
		s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "MLAT host or server is still down. Trying again in 5 minutes"
		sleep 5m
		exit 0
	fi
else
	rm -f "${MLAT_FLAG}"
fi

MLAT_PARAM=(--input-type "${MLAT_INPUT_TYPE}")
# MLAT_PARAM+=(--no-udp)
MLAT_PARAM+=(--input-connect "${MLAT_HOST}")
MLAT_PARAM+=(--server "${MLAT_SERVER}")
MLAT_PARAM+=(--lat "${LAT}")
MLAT_PARAM+=(--lon "${LON}")
MLAT_PARAM+=(--alt "${ALT}")
MLAT_PARAM+=(--results "${MLAT_RESULTS}")
MLAT_PARAM+=(--user "${FEEDER_KEY}")
MLAT_PARAM+=(--uuid "${FEEDER_KEY##*:}")
[[ -n "${PRIVATE_MLAT}" ]] && MLAT_PARAM+=(--privacy) || true

sleep ${START_DELAY}

if chk_enabled "${VERBOSE}"; then
	s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "Starting MLAT with: ${MLAT_CMD} ${MLAT_PARAM[@]}"
	exec s6wrap --quiet --prepend="${APPNAME}" --timestamps --args "${MLAT_CMD}" "${MLAT_PARAM[@]}"
else
	exec s6wrap --quiet --ignore=stdout --prepend="${APPNAME}" --timestamps --args "${MLAT_CMD}" "${MLAT_PARAM[@]}"
fi
