#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2145,SC2154

#---------------------------------------------------------------------------------------------
# Copyright (C) 2023-2024, Ramon F. Kolb (kx1t) and contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

source /scripts/common

START_DELAY=5s

RV_SERVER="${RV_SERVER:-mg22.adsbnetwork.com:50050}"
if [[ "${RV_SERVER%%:*}" == "mg2.adsbnetwork.com" ]]; then RV_SERVER="mg22.adsbnetwork.com:${RV_SERVER##*:}"; fi
"${s6wrap[@]}" echo "Started as an s6 service"

# check if we are in one of the defined zones, and update the server address accordingly:
source /home/zonetable
if [[ -n "$zone_id" ]]; then
  RV_SERVER="${zone_dns}:${zone_port}"
fi

sleep ${START_DELAY}
if chk_enabled "$VERBOSE"; then
  "${s6wrap[@]}" echo "Starting /home/py/ANfeeder -v -i \"${FEEDER_KEY}\" -d \"${RV_SERVER}\" -s \"${SOURCE_HOST}\""
  exec "${s6wrap[@]}" /home/py/ANfeeder -v -i "${FEEDER_KEY}" -d "${RV_SERVER}" -s "${SOURCE_HOST}"
else
  "${s6wrap[@]}" echo "Starting /home/py/ANfeeder -i \"${FEEDER_KEY}\" -d \"${RV_SERVER}\" -s \"${SOURCE_HOST}\""
  exec "${s6wrap[@]}" /home/py/ANfeeder -i "${FEEDER_KEY}" -d "${RV_SERVER}" -s "${SOURCE_HOST}"
fi
