#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2145,SC2154

#---------------------------------------------------------------------------------------------
# Copyright (C) 2023-2024, Ramon F. Kolb (kx1t) and contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

source /scripts/common
"${s6wrap[@]}" echo "Started as an s6 service"

START_DELAY=5s

if [[ "${RV_SERVER%%:*}" == "mg2.adsbnetwork.com" ]]; then RV_SERVER="mg22.adsbnetwork.com:${RV_SERVER##*:}"; fi

# Load the Zone Table:
source /home/zonetable

execstr=("/home/py/ANfeeder")
if chk_enabled "$VERBOSE"; then execstr+=("-v"); fi
execstr+=("-i ${FEEDER_KEY}")
execstr+=("-d ${zone_dns}:${zone_port}")
execstr+=("-s ${SOURCE_HOST}")

if [[ -n "$START_DELAY" ]]; then sleep "$START_DELAY"; fi

"${s6wrap[@]}" echo "Starting ${execstr[@]}"
# shellcheck disable=SC2068
exec "${s6wrap[@]}" ${execstr[@]}

