#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2145,SC2154

#---------------------------------------------------------------------------------------------
# Copyright (C) 2023-2024, Ramon F. Kolb (kx1t) and contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

source /scripts/common

START_DELAY=5s

export RV_LAT="${RV_LAT:-$LAT}"
export RV_LON="${RV_LON:-$LON}"
export RV_ALT="${RV_ALT:-$ALT}"

if [[ -n "$RV_SERVER" || -n "$FEEDER_KEY" ]]; then
    "${s6wrap[@]}" echo "-----------------------------------------------------------------------------"
    "${s6wrap[@]}" echo "ATTENTION - this container has been updated, but your environment variables"
    "${s6wrap[@]}" echo "are still reflecting the old configuration. Please update your configuration"
    "${s6wrap[@]}" echo "using this example: https://sdr-e.com/docker-radarvirtuel/blob/main/docker-compose.yml"
    "${s6wrap[@]}" echo "The container is HALTED until you make these updates."
    "${s6wrap[@]}" echo "-----------------------------------------------------------------------------"
    stop_service
fi

execstr="python3 -u /docker-entrypoint.py"

if [[ -n "$START_DELAY" ]]; then sleep "$START_DELAY"; fi

"${s6wrap[@]}" echo "Starting ${execstr[@]}"
# shellcheck disable=SC2068
exec "${s6wrap[@]}" ${execstr[@]}
