#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2145,SC2154

#---------------------------------------------------------------------------------------------
# Copyright (C) 2023-2024, Ramon F. Kolb (kx1t) and contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

source /scripts/common

if [[ -n "$RV_SERVER" || -n "$FEEDER_KEY" ]]; then
    stop_service
fi

export RV_LAT="${RV_LAT:-$LAT}"
export RV_LON="${RV_LON:-$LON}"
export BEASTHOST="${BEASTHOST:-${SOURCE_HOST:-ultrafeeder}}"
export BEASTPORT="${BEASTPORT:-${SOURCE_PORT:-30005}}"

if [[ -z "$RV_LAT" || -z "$RV_LON" ]]; then
    "${s6wrap[@]}" echo "RV_LAT (or LAT) and RV_LON (or LON) must be set to the feeder's location. Please check your configuration."
    stop_service
fi

if [[ -z "$BEASTHOST" ]]; then
    "${s6wrap[@]}" echo "BEASTHOST or SOURCE_HOST is not set. Defaulting to \"ultrafeeder\"."
    BEASTHOST="ultrafeeder"
fi

if [[ -z "$BEASTPORT" ]]; then
    "${s6wrap[@]}" echo "BEASTPORT (or SOURCE_PORT) is not set. Defaulting to \"30005\"."
    BEASTPORT="30005"
fi

"${s6wrap[@]}" echo "Started as an s6 service"

execstr="/usr/local/bin/readsb --net --quiet --lat ${RV_LAT} --lon ${RV_LON} --write-json=/run/readsb --json-reliable=1 --net-json-port=30047 --net-connector=${BEASTHOST},${BEASTPORT},beast_in --net-bo-port=30005"

"${s6wrap[@]}" echo "Starting ${execstr[@]}"
# shellcheck disable=SC2068
exec "${s6wrap[@]}" ${execstr[@]}
