#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2145,SC2154

source /scripts/common
ZONETABLE_CHECK_INT="${ZONETABLE_CHECK_INT:-14400}"	# check every 4 hours

"${s6wrap[@]}" echo "[INFO] checking if zonetable needs to get updated"

if curl -sSL https://raw.githubusercontent.com/sdr-enthusiasts/docker-radarvirtuel/zonetable/rootfs/home/zonetable -o /tmp/zonetable >/dev/null 2>&1; then 
	if [[ -n "$(comm -3 /home/zonetable /tmp/zonetable)" ]]; then
		"${s6wrap[@]}" echo "[INFO] zonetable has changed, installing new version"
		while [[ -f /run/zonetable.lock ]]; do sleep 1; done
		touch /run/zonetable.lock
	        mv -f /tmp/zonetable /home/zonetable
	        chmod +x /home/zonetable
		rm -f /run/zonetable.lock
	else
		"${s6wrap[@]}" echo "[INFO] zonetable has not changed since last check"
		rm -f /tmp/zonetable
	fi
else
	"${s6wrap[@]}" echo "[WARNING] couldn't reach the remote server with the latest zonetable - we will keep on using the current table"
fi

"${s6wrap[@]}" echo "[INFO] next zonetable update check will be at $(date -d "+$ZONETABLE_CHECK_INT seconds" | xargs)"
sleep $ZONETABLE_CHECK_INT
