#!/usr/bin/with-contenv bash
# shellcheck shell=bash

APPNAME="$(hostname)/mlat_client"
echo "[$APPNAME][$(date)] Started as an s6 service"

MLAT_CMD="/usr/bin/mlat-client"

[[ "${MLAT_INPUT_TYPE}" == "" ]] && MLAT_INPUT_TYPE=dump1090

MLAT_PARAM=(--input-type "${MLAT_INPUT_TYPE}")
# MLAT_PARAM+=(--no-udp)
MLAT_PARAM+=(--input-connect "${MLAT_HOST}")
MLAT_PARAM+=(--server "${MLAT_SERVER}")
MLAT_PARAM+=(--lat "${LAT}")
MLAT_PARAM+=(--lon "${LON}")
MLAT_PARAM+=(--alt "${ALT}")
MLAT_PARAM+=(--results beast,listen,50010)
MLAT_PARAM+=(--user "${FEEDER_KEY}")
if [[ ${PRIVATE_MLAT} == true ]]; then
    MLAT_PARAM+=(--privacy)
fi

set -eo pipefail
[[ "$VERBOSE" == "ON" ]] && echo "[$APPNAME][$(date)] Starting MLAT with: ${MLAT_CMD} ${MLAT_PARAM[@]}" || true
exec "${MLAT_CMD}" "${MLAT_PARAM[@]}" 2>&1 # | awk -v app="$APPNAME" -v d="$(date)" '{print "[" app "][" d "] " $1}'
