#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2145

source /scripts/common

APPNAME="radarvirtuel"
START_DELAY=5s

RV_SERVER="${RV_SERVER:-mg22.adsbnetwork.com:50050}"
[[ "${RV_SERVER%%:*}" == "mg2.adsbnetwork.com" ]] && RV_SERVER="mg22.adsbnetwork.com:${RV_SERVER##*:}" || true
s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "started as an s6 service"

sleep ${START_DELAY}
if [[ "$VERBOSE" == "ON" ]]
then
  exec s6wrap --quiet --prepend="${APPNAME}" --timestamps --args /home/py/ANfeeder -v -i "${FEEDER_KEY}" -d "${RV_SERVER}" -s "${SOURCE_HOST}"
else
  exec s6wrap --quiet --ignore=stdout --prepend="${APPNAME}" --timestamps --args /home/py/ANfeeder -i "${FEEDER_KEY}" -d "${RV_SERVER}" -s "${SOURCE_HOST}"
fi
