#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/imalive"
KEEPALIVE=600   # keepalive time in seconds

echo "[$APPNAME][$(date)]: Started as an s6 service"

while true
do
    echo "[$APPNAME][$(date)]: ImAlive watchdog will sleep for $KEEPALIVE secs"
    sleep $KEEPALIVE
    echo "[$APPNAME][$(date)]: Running ImAlive..."

    host=$HOSTNAME ;
    set $host;
    # kx1t: retrieve station name from $FEEDER_KEY docker env variable
    st=${FEEDER_KEY%%:*}
    ts=$(date "+%s")
    #echo " $st Current Time : $ts"
    STATUS=$(curl -s http://mg2.adsbnetwork.com:/rtools/pyalive.php?stid=$st);

    status="${STATUS%%-*}"
    rts="${STATUS##*-}"
    rts=$((rts-10));

    # check the ImAlive server:
    if [[ "$(echo $STATUS | grep -o "404")" == "404" ]]
    then
        echo  "[$APPNAME][$(date)]: Server returned 404-Not Found at $ts. Restarting ANFeeder \"just in case\"..."
        killall /home/py/ANfeeder
    elif [[ -z  $STATUS ]]
    then
        echo  "[$APPNAME][$(date)]: No Network at $ts. Restarting ANFeeder \"just in case\"..."
        killall /home/py/ANfeeder
    elif [[ $ts -lt $rts ]]
    then
        # kx1t: using s6 to restart the service instead of the RestartANfeeder.sh script
        echo "[$APPNAME][$(date)]: Time stamp discrepancy: Restart ANfeeder at date $ts "
        # kx1t: added warning that Docker image cannot resync NTP
        echo "[$APPNAME][$(date)]: Warning - Feeder script would like to resync NTP, but this cannot done from without a Docker container."
        killall /home/py/ANfeeder
        # /usr/bin/RestartANfeeder.sh majdate;
    elif [[ "$status" == "ko" ]]
    then
        # kx1t: using s6 to restart the service
        echo "[$APPNAME][$(date)]: Server says that no data is received: Restart ANfeeder at date $ts "
        killall /home/py/ANfeeder
        # /usr/bin/RestartANfeeder.sh;
    else
        echo "[$APPNAME][$(date)]: Server connection is fine! "
    fi

    # check the SOURCE_HOST
    if [[ $(timeout --preserve-status 5 netcat -z -v ${SOURCE_HOST%%:*} ${SOURCE_HOST##*:} 2>/dev/null ; echo $?) != "0" ]]
    then
        echo "[$APPNAME][$(date)]: You data source at $SOURCE_HOST appears to be down. Restarting ANfeeder at date $ts"
        killall /home/py/ANfeeder
    fi

    # check if the RV_SERVER can be reached
    if [[ $(timeout --preserve-status 5 netcat -u -z -v ${RV_SERVER%%:*} ${RV_SERVER##*:} 2>/dev/null ; echo $?) != "0" ]]
    then
        echo "[$APPNAME][$(date)]: The RadarVirtuel server at $RV_SERVER appears to be down. Restarting ANfeeder at date $ts"
        killall /home/py/ANfeeder
    fi

done
